
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - dash-network
  
  dash-app:
    entrypoint: ./entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8051:8051"
    depends_on:
      - mongodb
    env_file:
      - .env 
    networks:
      - dash-network

volumes:
  mongodb_data:

networks:
  dash-network:
    driver: bridge